name: Build

on:
  workflow_dispatch:
  push:
  pull_request:
    branches: [main]

env:
  APK_RELEASE_DIRECTORY: app/build/outputs/apk/release
  AAB_RELEASE_DIRECTORY: app/build/outputs/bundle/release
  BUILD_TOOLS_HOME: /usr/local/lib/android/sdk/build-tools

permissions:
  contents: read

jobs:
  build:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name != github.repository)
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: temurin
          cache: gradle

      - uses: gradle/actions/setup-gradle@v4

      - name: Release
        run: ./gradlew assembleRelease

      - name: Release bundle
        run: ./gradlew bundleRelease

      - name: Sign AAB
        run: |
          echo -n "${{ secrets.SIGNING_KEYSTORE }}" | base64 --decode >> $AAB_RELEASE_DIRECTORY/signingKey.jks
          jarsigner -keystore $AAB_RELEASE_DIRECTORY/signingKey.jks -storepass ${{ secrets.SIGNING_KEYSTORE_PASSWORD }} \
            -keypass ${{ secrets.SIGNING_ALIAS_PASSWORD }} $AAB_RELEASE_DIRECTORY/app-release.aab ${{ secrets.SIGNING_ALIAS }}
        continue-on-error: true

      - name: Upload App Bundle
        uses: actions/upload-artifact@v3
        with:
          name: app-release.aab
          path: ${{env.AAB_RELEASE_DIRECTORY}}/app-release.aab

      - name: Setup build tool version variable
        shell: bash
        run: |
          BUILD_TOOLS_VERSION=$(ls $BUILD_TOOLS_HOME | tail -1)
          echo "BUILD_TOOLS_PATH=$BUILD_TOOLS_HOME/$BUILD_TOOLS_VERSION" >> $GITHUB_ENV

      - name: Sign APK
        run: |
          echo -n "${{ secrets.SIGNING_KEYSTORE }}" | base64 --decode >> $APK_RELEASE_DIRECTORY/signingKey.jks
          ${{ env.BUILD_TOOLS_PATH }}/apksigner sign --ks $APK_RELEASE_DIRECTORY/signingKey.jks --ks-key-alias ${{ secrets.SIGNING_ALIAS }} \
            --ks-pass pass:${{ secrets.SIGNING_KEYSTORE_PASSWORD }} --key-pass pass:${{ secrets.SIGNING_ALIAS_PASSWORD }} \
            --out $APK_RELEASE_DIRECTORY/app-release-signed.apk \
            $APK_RELEASE_DIRECTORY/app-release.apk
          rm $APK_RELEASE_DIRECTORY/app-release.apk
        continue-on-error: true

      - name: Upload App Package
        uses: actions/upload-artifact@v3
        with:
          name: app-release-signed.apk
          path: ${{env.APK_RELEASE_DIRECTORY}}/app-release-signed.apk

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: ncipollo/release-action@v1
        with:
          artifacts: app/build/outputs/bundle/release/*.aab,app/build/outputs/apk/release/*.apk
          generateReleaseNotes: true
